### ISSUE TITLE
language switching option

### ISSUE THREAD

**Issue by bibin0baby** [frandiox/vue-use-stripe#5]
Can you let me know if the package has this option, or will you be adding this in future.

Thanks

**Comment by frandiox** [comment]
Hi. This is a simple wrapper around the original Stripe SDK. You can pass any option to the original constructor so I think we don't need to do anything in this library.

Maybe something like this:

```js
useStripe({
    key: process.env.VUE_APP_STRIPE_PUBLIC_KEY || '',
    elements: [{ type: 'card', options: {} }],
    constructorOptions: { locale: 'es' },
})
```
